UPDATE mcp_servers
SET
    scope = $2,
    owner_user_id = $3,
    source_endpoint_id = $4,
    name = $5,
    aggregate_naming_mode = $6,
    transport = $7,
    provider_kind = $8,
    url = $9,
    command = $10,
    args = $11,
    env_json = $12,
    bearer_tokens_json = $13,
    http_headers_json = $14,
    auth_mode = $15,
    basic_username = $16,
    basic_password = $17,
    proxy_url = $18,
    tool_filter_mode = $19,
    allowed_tools = $20,
    disabled_tools = $21,
    disabled_resources = $22,
    enabled = $23,
    timeout_ms = $24,
    lifecycle_policy = $25,
    lifecycle_manual_protocol_version = $26,
    updated_at = NOW()
WHERE server_id = $1
RETURNING server_id, source_endpoint_id, scope, owner_user_id, name, aggregate_naming_mode, transport, provider_kind, url, command, args, env_json, bearer_tokens_json, http_headers_json, auth_mode, basic_username, basic_password, proxy_url, (COALESCE(btrim(proxy_url), '') <> '') AS "has_proxy_url!", tool_filter_mode, allowed_tools, disabled_tools, disabled_resources, enabled, timeout_ms, lifecycle_policy, lifecycle_manual_protocol_version, lifecycle_learned_mode, lifecycle_learned_protocol_version, lifecycle_learned_for_updated_at, lifecycle_learned_at, created_at, updated_at
