use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use utoipa::OpenApi;

use super::doc_groups::{IdentityApiDoc, OperationsApiDoc, RoutingApiDoc};

const GENERATED_HEADER: &str = "# Generated by `cargo run -- openapi export`. DO NOT EDIT.\n";

#[derive(OpenApi)]
#[openapi(info(
    title = "prompt-ferry Admin API",
    version = "0.1.0",
    description = "Generated admin API snapshot exported from Rust handlers."
))]
struct RootApiDoc;

fn admin_api_doc() -> utoipa::openapi::OpenApi {
    let mut api = RootApiDoc::openapi();
    api.merge(IdentityApiDoc::openapi());
    api.merge(RoutingApiDoc::openapi());
    api.merge(OperationsApiDoc::openapi());
    api
}

pub fn export_admin_api(out: &str) -> Result<()> {
    let out_path = PathBuf::from(out);
    let parent = out_path
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent).with_context(|| {
        format!(
            "failed to create OpenAPI output directory {}",
            parent.display()
        )
    })?;

    let yaml = admin_api_doc()
        .to_yaml()
        .context("failed to serialize OpenAPI document to yaml")?;
    fs::write(&out_path, format!("{GENERATED_HEADER}{yaml}"))
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(())
}
