use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use utoipa::OpenApi;

use super::{
    billing::BillingApiDoc,
    doc_groups::{IdentityApiDoc, OperationsApiDoc, RoutingApiDoc},
    relay_management::RelayApiDoc,
};

const GENERATED_HEADER: &str = "# Generated by `cargo run -- openapi export`. DO NOT EDIT.\n";

#[derive(OpenApi)]
#[openapi(info(
    title = "prompt-ferry Admin API",
    version = "0.1.0",
    description = "Generated admin API snapshot exported from Rust handlers."
))]
struct RootApiDoc;

fn admin_api_doc() -> utoipa::openapi::OpenApi {
    let mut api = RootApiDoc::openapi();
    api.merge(IdentityApiDoc::openapi());
    api.merge(RoutingApiDoc::openapi());
    api.merge(OperationsApiDoc::openapi());
    api.merge(BillingApiDoc::openapi());
    api.merge(RelayApiDoc::openapi());
    api
}

pub fn export_admin_api(out: &str) -> Result<()> {
    let out_path = PathBuf::from(out);
    let parent = out_path
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent).with_context(|| {
        format!(
            "failed to create OpenAPI output directory {}",
            parent.display()
        )
    })?;

    let yaml = admin_api_doc()
        .to_yaml()
        .context("failed to serialize OpenAPI document to yaml")?;
    fs::write(&out_path, format!("{GENERATED_HEADER}{yaml}"))
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{GENERATED_HEADER, admin_api_doc};
    use std::path::PathBuf;
    use utoipa::openapi::{PathItem, path::Operation};

    /// The operation a documented path carries for `method`.
    fn operation<'a>(item: &'a PathItem, method: &str) -> Option<&'a Operation> {
        match method {
            "get" => item.get.as_ref(),
            "post" => item.post.as_ref(),
            "patch" => item.patch.as_ref(),
            "put" => item.put.as_ref(),
            other => panic!("unsupported method {other}"),
        }
    }

    /// The checked-in spec must be exactly what this exporter produces.
    ///
    /// The file carries a `DO NOT EDIT` header, so anything other than a fresh
    /// export is a hand edit that a later export will silently drop. Asserting
    /// byte identity here is what makes "regenerate, do not edit" enforceable
    /// rather than a convention.
    #[test]
    fn the_checked_in_spec_is_byte_identical_to_a_fresh_export() {
        let generated = format!(
            "{GENERATED_HEADER}{}",
            admin_api_doc()
                .to_yaml()
                .expect("the API document serializes")
        );
        let checked_in = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("openapi/admin-api.yaml");
        let committed = std::fs::read(&checked_in)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", checked_in.display()));

        assert_eq!(
            String::from_utf8_lossy(&committed),
            generated,
            "{} is out of date; run `cargo run -- openapi export` and commit the result",
            checked_in.display()
        );
    }

    /// Every relay management route the listener serves is in the spec.
    ///
    /// The relay's routes are exported from a separate tree, so a route added
    /// without its stub would leave the spec and the generated client silently
    /// missing it.
    #[test]
    fn the_relay_management_api_is_exported_from_its_own_source() {
        let document = admin_api_doc();
        let paths = &document.paths.paths;

        for (path, method) in [
            ("/api/v1/relay/auth/login", "post"),
            ("/api/v1/relay/auth/logout", "post"),
            ("/api/v1/relay/auth/me", "get"),
            ("/api/v1/relay/status", "get"),
            ("/api/v1/relay/settings", "get"),
            ("/api/v1/relay/settings", "patch"),
            ("/api/v1/relay/host", "get"),
            ("/api/v1/relay/host/role", "put"),
            ("/api/v1/relay/host/restart", "post"),
        ] {
            let item = paths
                .get(path)
                .unwrap_or_else(|| panic!("{path} is missing from the exported API"));
            let operation = operation(item, method)
                .unwrap_or_else(|| panic!("{method} {path} is missing from the exported API"));
            assert_eq!(
                operation
                    .tags
                    .as_ref()
                    .and_then(|tags| tags.first())
                    .map(String::as_str),
                Some("relay"),
                "{method} {path} must be documented under the relay tag"
            );
        }

        let schemas = &document
            .components
            .as_ref()
            .expect("components are exported")
            .schemas;
        for schema in [
            "RelayAuthResponse",
            "RelayConfigView",
            "RelayHostResponse",
            "RelayHostRoleRequest",
            "RelayLoginRequest",
            "RelaySettingsResponse",
            "RelaySettingsUpdate",
            "RelayStatusResponse",
            "WorkerStatusResponse",
            "HostRole",
        ] {
            assert!(
                schemas.contains_key(schema),
                "the exported API is missing the {schema} schema"
            );
        }
    }
}
