update managed_relays
set
  name = $2,
  relay_url = $3,
  enabled = $4,
  tls_mode = $5,
  bridge_encryption_mode = $6,
  relay_ca_ciphertext = $7,
  relay_ca_nonce = $8,
  relay_ca_key_version = $9,
  client_cert_ciphertext = $10,
  client_cert_nonce = $11,
  client_cert_key_version = $12,
  client_key_ciphertext = $13,
  client_key_nonce = $14,
  client_key_key_version = $15,
  bridge_encryption_key_ciphertext = $16,
  bridge_encryption_key_nonce = $17,
  bridge_encryption_key_key_version = $18,
  updated_at = now()
where relay_id = $1
returning
  relay_id,
  name,
  relay_url,
  enabled,
  tls_mode,
  bridge_encryption_mode,
  relay_ca_ciphertext,
  relay_ca_nonce,
  relay_ca_key_version,
  client_cert_ciphertext,
  client_cert_nonce,
  client_cert_key_version,
  client_key_ciphertext,
  client_key_nonce,
  client_key_key_version,
  bridge_encryption_key_ciphertext,
  bridge_encryption_key_nonce,
  bridge_encryption_key_key_version,
  created_at,
  updated_at;
