INSERT INTO approval_requests (
    approval_id,
    request_id,
    user_id,
    client_key_label,
    path,
    model,
    review_decision,
    approval_status,
    review_reason,
    review_categories,
    request_preview,
    request_payload_json,
    request_deadline_unix_ms,
    wait_deadline_unix_ms
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING
    approval_id,
    request_id,
    user_id,
    (SELECT login_name FROM users WHERE user_id = approval_requests.user_id) AS "user_login_name?",
    client_key_label,
    path,
    model,
    review_decision,
    approval_status,
    review_reason,
    review_categories,
    request_preview,
    request_payload_json,
    request_deadline_unix_ms,
    wait_deadline_unix_ms,
    decided_by_user_id,
    (SELECT login_name FROM users WHERE user_id = approval_requests.decided_by_user_id) AS "decided_by_login_name?",
    decided_at,
    created_at,
    updated_at
