INSERT INTO standalone_mcp_servers(
    server_id, source_endpoint_id, scope, owner_user_id, name,
    aggregate_naming_mode, transport, url, command, args_json,
    http_headers_json, tool_filter_mode, allowed_tools_json,
    disabled_tools_json, disabled_resources_json, daily_max_requests,
    monthly_max_requests, enabled, timeout_ms, lifecycle_policy,
    lifecycle_manual_protocol_version, lifecycle_learned_mode,
    lifecycle_learned_protocol_version, lifecycle_learned_for_updated_at,
    lifecycle_learned_at, env_ciphertext, env_nonce, env_key_version,
    bearer_tokens_ciphertext, bearer_tokens_nonce, bearer_tokens_key_version,
    created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(server_id) DO UPDATE SET
    source_endpoint_id = excluded.source_endpoint_id,
    scope = excluded.scope,
    owner_user_id = excluded.owner_user_id,
    name = excluded.name,
    aggregate_naming_mode = excluded.aggregate_naming_mode,
    transport = excluded.transport,
    url = excluded.url,
    command = excluded.command,
    args_json = excluded.args_json,
    http_headers_json = excluded.http_headers_json,
    tool_filter_mode = excluded.tool_filter_mode,
    allowed_tools_json = excluded.allowed_tools_json,
    disabled_tools_json = excluded.disabled_tools_json,
    disabled_resources_json = excluded.disabled_resources_json,
    daily_max_requests = excluded.daily_max_requests,
    monthly_max_requests = excluded.monthly_max_requests,
    enabled = excluded.enabled,
    timeout_ms = excluded.timeout_ms,
    lifecycle_policy = excluded.lifecycle_policy,
    lifecycle_manual_protocol_version = excluded.lifecycle_manual_protocol_version,
    lifecycle_learned_mode = excluded.lifecycle_learned_mode,
    lifecycle_learned_protocol_version = excluded.lifecycle_learned_protocol_version,
    lifecycle_learned_for_updated_at = excluded.lifecycle_learned_for_updated_at,
    lifecycle_learned_at = excluded.lifecycle_learned_at,
    env_ciphertext = excluded.env_ciphertext,
    env_nonce = excluded.env_nonce,
    env_key_version = excluded.env_key_version,
    bearer_tokens_ciphertext = excluded.bearer_tokens_ciphertext,
    bearer_tokens_nonce = excluded.bearer_tokens_nonce,
    bearer_tokens_key_version = excluded.bearer_tokens_key_version,
    updated_at = excluded.updated_at;
