//! Frontend assets embedded in the prompt-ferry binary.
//!
//! The production binary and the container image carry one artifact: the built
//! SPA under `frontend/dist` is compiled into the executable, so no runtime
//! frontend directory has to exist beside it. A development checkout overrides
//! this deliberately with [`FRONTEND_DIST_ENV`] (or the historical filesystem
//! locations) so an iteration loop does not require a rebuild.
//!
//! Embedding happens through `include_dir`, which resolves the directory at
//! compile time; a source checkout without `frontend/dist` still compiles for
//! backend-focused Rust work and then serves a deliberate fallback page instead
//! of silently shipping a half-built UI.

use include_dir::{Dir, include_dir};

/// Environment variable pointing at a filesystem frontend `dist` directory.
///
/// The override is deliberate and developer-facing: an explicitly configured
/// directory is honoured even when the embedded assets exist, so frontend work
/// can skip the Rust rebuild.
pub const FRONTEND_DIST_ENV: &str = "PROMPT_FERRY_FRONTEND_DIST";

/// The SPA build output captured at compile time.
///
/// `frontend/dist` is generated by the frontend build and never committed. When
/// it is absent — a backend-focused source checkout — this is an empty
/// directory and [`embedded_index`] falls back to a page that says so.
static EMBEDDED_FRONTEND: Dir = include_dir!("$CARGO_MANIFEST_DIR/frontend/dist");

/// The built SPA served from the binary when no filesystem override applies.
pub fn embedded_assets() -> &'static Dir<'static> {
    &EMBEDDED_FRONTEND
}

/// Whether the compile-time capture actually contains a built frontend.
pub fn has_embedded_index() -> bool {
    EMBEDDED_FRONTEND.get_file("index.html").is_some()
}

/// `index.html` from the embedded assets, or a fallback page explaining that
/// the frontend was not built into this binary.
///
/// The fallback keeps `cargo run` and backend-only release builds honest:
/// navigating to the admin root returns `200` with an actionable message
/// rather than an empty document.
pub fn embedded_index() -> &'static [u8] {
    match EMBEDDED_FRONTEND.get_file("index.html") {
        Some(file) => file.contents(),
        None => FALLBACK_INDEX_HTML.as_bytes(),
    }
}

/// Look up one embedded file by its path inside `frontend/dist`.
pub fn embedded_file(path: &str) -> Option<&'static [u8]> {
    EMBEDDED_FRONTEND.get_file(path).map(|file| file.contents())
}

/// One hashed JavaScript asset from the embedded tree, wherever it sits.
///
/// A test-only convenience: the built asset names change with their contents,
/// so tests discover one instead of hard-coding a hash.
#[cfg(test)]
pub(crate) fn hashed_js_asset_path() -> Option<&'static str> {
    fn walk(dir: &'static Dir<'static>) -> Option<&'static str> {
        for file in dir.files() {
            let path = file.path().to_str()?;
            if path.starts_with("assets/") && path.ends_with(".js") {
                return Some(path);
            }
        }
        dir.dirs().find_map(walk)
    }
    walk(&EMBEDDED_FRONTEND)
}

const FALLBACK_INDEX_HTML: &str = r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>prompt-ferry</title>
  </head>
  <body>
    <h1>prompt-ferry admin UI is not built into this binary</h1>
    <p>
      This prompt-ferry binary was compiled without the frontend build output
      (<code>frontend/dist</code>), so the admin UI is not embedded. The Admin
      API below <code>/api/v1</code> is fully available.
    </p>
    <p>To embed the UI, build the frontend and recompile the binary:</p>
    <pre><code>cd frontend &amp;&amp; bun install &amp;&amp; bun run build
cargo build --release</code></pre>
    <p>
      For development without recompiling, point
      <code>PROMPT_FERRY_FRONTEND_DIST</code> at a frontend <code>dist</code>
      directory.
    </p>
  </body>
</html>
"#;

#[cfg(test)]
mod tests {
    use super::{
        FALLBACK_INDEX_HTML, FRONTEND_DIST_ENV, embedded_assets, embedded_file, embedded_index,
        has_embedded_index,
    };

    #[test]
    fn embedded_assets_contain_the_spa_entry_when_the_frontend_was_built() {
        let assets = embedded_assets();
        if !has_embedded_index() {
            // A backend-focused checkout: the fallback contract is what matters.
            assert_eq!(
                embedded_index(),
                FALLBACK_INDEX_HTML.as_bytes(),
                "a checkout without frontend/dist must serve the fallback page"
            );
            assert_eq!(embedded_file("index.html"), None);
            return;
        }

        let index = embedded_index();
        let html = std::str::from_utf8(index).expect("index.html is UTF-8");
        assert!(html.contains("<script"), "built index.html loads the SPA");
        assert!(
            html.contains("assets/"),
            "built index.html references hashed assets"
        );
        assert!(embedded_file("favicon.svg").is_some());
        assert!(
            assets
                .dirs()
                .any(|dir| dir.path() == std::path::Path::new("assets")),
            "the built dist carries an assets directory"
        );
    }

    #[test]
    fn a_missing_embedded_file_is_none_without_panicking() {
        assert_eq!(embedded_file("no/such/file.js"), None);
    }

    #[test]
    fn the_fallback_page_names_the_remedy_without_leaking_state() {
        let html = FALLBACK_INDEX_HTML;
        assert!(html.contains("not built into this binary"));
        assert!(html.contains(FRONTEND_DIST_ENV));
        // The fallback is static and carries no build-specific content.
        assert!(!html.contains("assets/"));
    }

    #[test]
    fn the_build_never_depends_on_a_generated_dist_being_committed() {
        // build.rs creates `frontend/dist` when the SPA build has not run, so
        // `include_dir!` always captures a directory and this module compiles
        // on a clean checkout either way.
        let dist = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("frontend/dist");
        assert!(
            dist.is_dir(),
            "build.rs must leave a frontend/dist directory in place"
        );
    }

    #[test]
    fn the_override_env_name_is_stable() {
        // The name is operator-facing configuration; it may not drift silently.
        assert_eq!(FRONTEND_DIST_ENV, "PROMPT_FERRY_FRONTEND_DIST");
    }
}
